name: generate-linkedin-draft

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 */3 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Show repo tree
        run: |
          pwd
          ls -la
          echo "---- app ----"
          ls -la app || true
          echo "---- app/sources ----"
          ls -la app/sources || true
          echo "---- app/write ----"
          ls -la app/write || true
          echo "---- app/images ----"
          ls -la app/images || true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip and install deps
        run: |
          python -V
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip freeze

      - name: Run generator (show full traceback)
        run: |
          set -x
          python app/main.py

      - name: Commit artifacts (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add out/ || true
          git commit -m "Auto: new LinkedIn draft" || echo "Nothing to commit"
          git push
